###회원가입 
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "email" : "email14",
  "nickname": "testuser14",
  "password": "testpassword14"
}

###로그인 (ACCESSTOKEN 발급)

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "nickname": "testuser14",
  "password": "testpassword14"
}


###
#상품등록 
POST http://localhost:3000/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
Content-Type: application/json

{
  "name" : "바뀐의제품344", 
  "description" : "최신형이에요", 
  "price" : 33032000, 
  "tags": ["가성비"]
}

###
#상품수정 
PATCH http://localhost:3000/product/change/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
Content-Type: application/json

{
  "name" : "세탁기31233", 
  "description" : "상태안좋아요", 
  "price" : 230000, 
  "tags": ["가성비"]
}

###
#상품삭제
DELETE http://localhost:3000/product/remove/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8

###
#상품목록조회
GET http://localhost:3000/product/list


###
#게시글 등록
POST http://localhost:3000/article/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI
Content-Type: application/json

{
  "title" : "게시글 디토", 
  "content" : "test내용231"
}
###
#게시글 수정
PATCH  http://localhost:3000/article/change/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI
Content-Type: application/json

{
  "title" : "수정된제목2321", 
  "content" : "수정된내용1"
}

###
#게시글 삭제
DELETE http://localhost:3000/article/remove/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI

###
#게시글 조회
GET http://localhost:3000/article/list 



###
#중고마켓 댓글 등록
POST http://localhost:3000/comment/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
Content-Type: application/json

{
  "product_id" : 1,
  "content" : "댓글쓸게요"
}

###
#게시판 댓글 등록
POST http://localhost:3000/comment/article/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
Content-Type: application/json

{
  "article_id" : 3,
  "content" : "게시판에 댓글쓸게요"
}

###
#댓글 수정
PATCH  http://localhost:3000/comment/change/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
Content-Type: application/json

{
  "content" : "14번글댓글수정16번유저"
}


###
#댓글 삭제
DELETE http://localhost:3000/comment/remove/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8

###
#중고마켓 댓글 조회 

GET http://localhost:3000/comment/product/list


###
#게시판 댓글 조회 
GET http://localhost:3000/comment/article/list


###
#유저 정보 조회 
GET http://localhost:3000/users/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg3MDQ3MiwiZXhwIjoxNzUxODc0MDcyfQ.stE2M8ZCpW2u2DuX1TPxHXhVoChH3PTo9X8zL7ZJog8
###
#유저 정보 수정
PATCH http://localhost:3000/users/change
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzUwOTA1ODY2LCJleHAiOjE3NTA5OTIyNjZ9.F_Jp8GWYh7mbeF4fCru0hqw07VOzhuXQechWTTdxsTg
Content-Type: application/json

{
  "email" : "email수정",
  "nickname" : "아이디수정",
  "password" : "비밀번호수정",
  "image" : "이미지수정"
}

###
#유저 상품 조회 
GET http://localhost:3000/users/productList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUwOTM0NjgyLCJleHAiOjE3NTA5MzgyODJ9.QcDiuClSYio3t_0aTgUQBwR_w5LS4-QFl6pIcL0BKkQ
###
# refresh 토큰 
POST http://localhost:3000/users/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1MDkxOTIwNywiZXhwIjoxNzUxNTI0MDA3fQ.v-BguPeGEZOx3jAxzwNVUG1qnZioYmLjTTQtMJfB2fA



###
# 상품 좋아요 추가
POST http://localhost:3000/product/likes/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1MDk4OTk0NiwiZXhwIjoxNzUwOTkzNTQ2fQ.P_ypldEbEH3Fo4u5wpbwJ4P27HWraVddCCbiPwptw1A

###
# 상품 좋아요 취소 
DELETE http://localhost:3000/product/likesCancel/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUwOTM0NjgyLCJleHAiOjE3NTA5MzgyODJ9.QcDiuClSYio3t_0aTgUQBwR_w5LS4-QFl6pIcL0BKkQ

###
# 게시글 좋아요 추가
POST http://localhost:3000/article/likes/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI

###
# 게시글 좋아요 취소 
DELETE http://localhost:3000/article/likesCancel/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI


###
# 유저가 좋아요한 상품목록 조회
GET http://localhost:3000/product/likesList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1MDk5OTY2OSwiZXhwIjoxNzUxMDAzMjY5fQ.OofHBi7lbal8EbTL779JI57NJ-ObH4kSj0f497ovSeI

###
# 유저가 좋아요 했는지 안했는지 상품 목록 조회 ( isLiked )
GET http://localhost:3000/product/isLiked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc1MDk5OTY2OSwiZXhwIjoxNzUxMDAzMjY5fQ.OofHBi7lbal8EbTL779JI57NJ-ObH4kSj0f497ovSeI


###
# 유저가 좋아요 했는지 안했는지 게시글 목록 조회 ( isLiked )
GET http://localhost:3000/article/isLiked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTc1MTg2NzI5MCwiZXhwIjoxNzUxODcwODkwfQ.CI1oAMuHr0By_xNfW3WRmi8vFGf4o3KhaJyVHtwJZEI
