name : Deploy to AWS

on: 
  push:
    branches: ["main"]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      # AWS 배포변수
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/2-sprint-mission
            git pull origin main
            npm install --production
            npm run build
            pm2 restart all || pm2 start dist/server.js --name used-shop
